OCAML_SOURCE = ocaml-3.12.0
TRECS = trecs-1.22
CSISAT = csisat-read-only
ATP = /usr/lib/ocaml/atp
APRON = /usr/local/lib
GMP = /usr/lib

# OCAML_SOURCE = ocaml-3.12.0
# TRECS = trecs-1.22
# CSISAT = csisat-read-only
# ATP = atp
# APRON = /usr/local/lib/ocaml/3.12.0/apron
# GMP = /usr/local/lib/ocaml/3.12.0/gmp
