#!/bin/sh
#*********************************************************************#
#                                                                     #
#                           Objective Caml                            #
#                                                                     #
#                    Pierre Weis, INRIA Rocquencourt                  #
#                                                                     #
#  Copyright 2008 Institut National de Recherche en Informatique et   #
#  en Automatique.  All rights reserved.  This file is distributed    #
#  only by permission.                                                #
#                                                                     #
#*********************************************************************#

# $Id: clean,v 1.1 2008-09-13 16:35:53 weis Exp $

# A simple script to clean this directory.

/bin/rm -rf *.cm* *.o a.out *~
/bin/rm -rf sudoku sudoku.byt sudoku.bin
/bin/rm -rf types.ml
