#!/bin/sh

dir=`dirname $0`
lib=$dir/lib
bin=$dir/bin
stdlib=$dir/stdlib

ld="$lib/ld-linux-x86-64.so.2 --library-path $lib"
horsat="$ld $bin/horsat"
horsat2="$ld $bin/horsat2"
horsatp="$ld $bin/horsatp"
trecs="$ld $bin/trecs"
cvc3=$bin/cvc3

$ld $bin/mochi.opt -trecs-bin "$trecs" -horsat-bin "$horsat" -horsat2-bin "$horsat2" -horsatp-bin "$horsatp" -cvc3-bin "$cvc3" -I $stdlib "$@"
