#!/bin/sh

ocamlc -c parsetree.mli
ocamlyacc -v parser.mly
ocamlc -c parser.mli
ocamllex lexer.mll
ocamlc -c lexer.ml
ocamlc -c parser.ml
ocamlc -c scoping.mli
ocamlc -c scoping.ml
ocamlc -c print_ast.mli
ocamlc -c print_ast.ml
ocamlc -c treat.mli
ocamlc -c treat.ml
ocamlc -c main.ml
ocamlc -o polish lexer.cmo parser.cmo scoping.cmo print_ast.cmo treat.cmo main.cmo
